### ISSUE TITLE
opening the codesandbox link immediately renders an error

### ISSUE THREAD

**Issue by reblairshopr** [edmundhung/remix-sandbox#25]
https://codesandbox.io/s/github/edmundhung/remix-sandbox

<img width="1285" alt="Screen Shot 2021-11-16 at 3 29 46 PM" src="https://user-images.githubusercontent.com/93352254/142082583-5e7ecf3e-9fa7-4180-8d55-0a913ab3ec5f.png">

**Comment by edmundhung** [comment]
Hi @reblairshopr ! Thanks for reporting this. It looks like Codesandbox fails to load any files from Github and so it fails to run it properly. It might be related to their incident today. I will keep the issues open and check again tomorrow.

**Comment by edmundhung** [comment]
It is working for me now with the latest remix version just released 2 mins ago :fire:

**Comment by reblairshopr** [comment]
Sweet thanks!
